# ==================================================
# =      Spring Profile for Local Development      =
# = (Activated by default in application.yml)    =
# ==================================================

spring:
  # ===============================
  # =       Database (MySQL)      =
  # ===============================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 Docker 컨테이너의 MySQL 서버에 연결합니다.
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      # 로컬 개발 환경에서는 update로 설정하여 애플리케이션 실행 시 스키마를 자동으로 갱신합니다.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 방언 설정
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  # ===============================
  # =      Redis (Enabled)        =
  # ===============================
  data:
    redis:
      # local 프로필에서 Redis 활성화
      enabled: true
      # 로컬 Docker 컨테이너의 Redis 서버에 연결합니다.
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    # local 프로필에서 cache 저장소로 Redis 사용
    type: redis
