# ==================================================
# = Spring Profile for Development/Production Env  =
# =      (Activate with --spring.profiles.active=dev)      =
# ==================================================

spring:
  # ===============================
  # =       Database (MySQL)      =
  # ===============================
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    timescaledb:
      driver-class-name: org.postgresql.Driver
      url: ${TIMESCALEDB_URL}
      username: ${TIMESCALEDB_USER}
      password: ${TIMESCALEDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # 운영 환경에서는 validate 또는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 방언 설정

  # ===============================
  # =      Redis (Enabled)        =
  # ===============================
  data:
    redis:
      enabled: true
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
